#
dev: nobody

name: Demo Slot

description: Slot demo gacor melatih pola permainan

poster: /assets/images/dafftube.png

avatar: /assets/images/logo_img.png

iklanVideo: https://www.xnxx.com/embedframe/ubuhvlb115b

disqus:

google_analytics: G-MBYBX123VX

url: https://xoilack.github.io

baseurl: "/indoasasaf"

permalink: /ID-id/:title

version: v1.2.0

kramdown:

  input: GFM

  syntax_highlighter: rouge
  syntax_highlighter_opts:

    css_class: 'highlight'

sass:
  style: :expanded

# Google Auth
WA_KEY: 0000000000
SITE_KEY: 6LdwSAMqAAAAAJNf2-neEbSjXLJyz6O2d3LF6Ifa
API_KEY: AIzaSyASDvwpm5L68N_CmQvOCxgLqiR-ZfPrpTs
AUTH_DOMAIN: anjim-3f8ed.firebaseapp.com
DATABASE_URL: https://anjim-3f8ed-default-rtdb.firebaseio.com/
PROJECT_ID: anjim-3f8ed
STORAGE_BUCKET: anjim-3f8ed.firebasestorage.app
SENDER_ID: 915430992427
APP_ID: 1:915430992427:web:d205b4a7918f142e34986e
MEASUREMENT_ID: G-L4XJ7N37QP

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sass-converter

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
